{{- if and .Values.mlTrainer.enabled .Values.mlTrainer.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mlTrainer.name }}-models
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.mlTrainer.name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.mlTrainer.persistence.size }}
{{- end }}