apiVersion: v2
name: dota2-meta-lab
description: A Helm chart for Dota 2 Meta Lab Platform
type: application
version: 0.1.0
appVersion: "1.0"

keywords:
  - dota2
  - machine-learning
  - analytics

maintainers:
  - name: Rina Villaruz
    email: tropes.hunger0c@icloud.com